# Generated by Django 2.2.2 on 2019-09-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemenu',
            name='TeaName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemenu',
            name='TeaPrice',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
