# Generated by Django 2.2.2 on 2019-09-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20190928_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_TeaName', models.CharField(max_length=50)),
                ('TeaPrice', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('PassWord', models.CharField(max_length=20)),
                ('PhoneNumber', models.IntegerField(max_length=12)),
            ],
        ),
    ]
