# Generated by Django 2.2.2 on 2019-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_orders_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.IntegerField(max_length=50)),
                ('Order_tea', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
