# Generated by Django 2.2.2 on 2019-09-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_userpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='menucard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeaName', models.CharField(max_length=50)),
                ('TeaPrice', models.IntegerField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
