# Generated by Django 2.2.2 on 2019-09-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_menucard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menucard',
        ),
        migrations.DeleteModel(
            name='UserPattern',
        ),
        migrations.RenameField(
            model_name='homemenu',
            old_name='description',
            new_name='Description',
        ),
    ]
